[package]
name = "notsure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.28"
glow = "0.11"
confindent = "2.0"
thiserror = "1.0"